#Eliza
# 6/7/2021
print("Welcome to My Game! Please enter one of the menu options.")
print()
print()
print()
print()
print()
print()
print()
print()

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("~                             ~")
print("~          My Game!           ~")
print("~                             ~")
print("~            Menu             ~")
print("~                             ~")
print("~        Level: Easy          ~")
print("~    Level: Intermediate      ~")
print("~      Level: Advanced        ~")
print("~         Exit Game           ~")
print("~                             ~")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

word=str(input())
print ()
while "Level" in word:
    print("You are now playing", word)
    print()
    print()
    print()
    print("game over")
    print()
    print()
    print()
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~                             ~")
    print("~          My Game!           ~")
    print("~                             ~")
    print("~            Menu             ~")
    print("~                             ~")
    print("~        Level: Easy          ~")
    print("~    Level: Intermediate      ~")
    print("~      Level: Advanced        ~")
    print("~         Exit Game           ~")
    print("~                             ~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("type menu option")
    word=str(input())
print()
print()
print("Thank you for playing My Game!")

